flagging/urls.py
from django.urls import path

from .views import SetFlag


app_name = 'flagging'

urlpatterns = [
    path('', SetFlag.as_view(), name='flag'),
]

notifications/urls.py
from django.urls import re_path as pattern

from . import views


app_name = 'notifications'

urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<id>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<id>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

rml/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _

import core.urls


urlpatterns = [
	path('i18n/', include('django.conf.urls.i18n')),
	path('activity', include('actstream.urls')),
	path('grappelli/', include('grappelli.urls')),
	path('',  include(core.urls)),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('accounts/'), include('allauth.urls')),

)


if not settings.USE_S3:
	from django.conf.urls.static import static

	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
	# import debug_toolbar

	# urlpatterns = [
	# 				  path('__debug__/', include(debug_toolbar.urls)),
	# 			  ] + urlpatterns
    pass

flagging/models/models.py
from collections import namedtuple
from enum import IntEnum, unique
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from .operations import FlagOperations
from ..managers import FlagInstanceManager, FlagManager

User = settings.AUTH_USER_MODEL


class Flag(models.Model, FlagOperations):
    """
    Used to add flag/moderation to a model. 
    Use on models with a "poster" field or attribute and corresponding 'poster_id' attribute. 
    This attribute is used to get the user that created the flagged content.
    """
    
    @unique
    class State(IntEnum):
        UNFLAGGED = 1
        FLAGGED = 2
        REJECTED = 3
        NOTIFIED = 4
        RESOLVED = 5

    STATE_CHOICES = [
        (State.UNFLAGGED.value, _('Unflagged')),
        (State.FLAGGED.value, _('Flagged')),
        (State.REJECTED.value, _('Flag rejected by the moderator')),
        (State.RESOLVED.value, _('Content modified by the author')),
        (State.NOTIFIED.value, _('Creator notified')),
    ]

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    # Flagged object
    content_object = GenericForeignKey('content_type', 'object_id')
    # User who has the post
    creator = models.ForeignKey(
        User, 
        related_name='flags_against', 
        null=True, blank=True, 
        on_delete=models.CASCADE
    )
    state = models.SmallIntegerField(choices=STATE_CHOICES, default=State.UNFLAGGED.value)
    moderator = models.ForeignKey(
        User, 
        null=True, blank=True, 
        related_name='flags_moderated', 
        on_delete=models.SET_NULL
    )
    count = models.PositiveIntegerField(default=0)

    objects = FlagManager()

    @property
    def is_flagged(self):
        """
        Return if flag is flagged or not. Flag is considered flag 
        if its count is > MAX_FLAGS_ALLOWED.
        Note that the flags state is updated when toggle_flagged_state() is called, 
        and the latter is called after every new FlagInstance is created.
        """
        return self.state != self.State.UNFLAGGED.value

    class Meta:
        db_table = 'flagging\".\"flag'
        verbose_name = _('Flag')
        constraints = [
            models.UniqueConstraint(
                fields=['content_type', 'object_id'],
                name='unique_content_type_and_object_id'
            )
        ]


class FlagInstance(models.Model):
    # Flag reasons
    @unique
    class FlagReason(IntEnum):
        SPAM = 1
        EXPLICIT = 2
        HATE_SPEECH = 3
        VIOLENCE = 4
        HARASSMENT = 5
        
    # Reasons displayed when flagging an object
    FLAG_REASONS = [
        (FlagReason.SPAM.value, _('Unwanted commercial content or spam')),
        (FlagReason.EXPLICIT.value, _('Pornography or sexually explicit content')),
        (FlagReason.HATE_SPEECH.value, _('Hate speech or graphic violence')),
        (FlagReason.VIOLENCE.value, _('Abusive or intended at promoting hatred')),
        (FlagReason.HARASSMENT.value, _('Harassment or bullying')),
    ]

    # Make a named tuple
    Reasons = namedtuple('Reason', ['value', 'reason'])

    # Construct the list of named tuples
    reasons = []
    for reason in FLAG_REASONS:
        reasons.append(Reasons(*reason))

    reason_values = [reason.value for reason in reasons]

    flag = models.ForeignKey(
        Flag, 
        related_name='flags', 
        related_query_name='flag_instance',
        on_delete=models.CASCADE,
        db_column='flag_id'
    )
    # User that created the flag
    user = models.ForeignKey(
        User, 
        related_name='created_flag_instances', 
        related_query_name='flag_instance',
        on_delete=models.CASCADE
    )
    flagged_on = models.DateTimeField(auto_now_add=True)
    reason = models.SmallIntegerField(choices=FLAG_REASONS, default=reason_values[0])

    objects = FlagInstanceManager()

    class Meta:
        db_table = 'flagging\".\"flag_instance'
        ordering = ['-flagged_on']
        indexes = [
            models.Index(
                fields=['-flagged_on'],
                name='flag_instance_date_desc_idx'
            )
        ]
        constraints = [
            models.UniqueConstraint(
                fields=['flag', 'user'],
                name='unique_user_and_flag_instance'
            )
        ]
        verbose_name = _('Flag Instance')
        verbose_name_plural = _('Flag Instances')

flagging/models/operations.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

from ..constants import CONTENT_IS_FLAGGED_COUNT


class FlagOperations:
    """Mixin for operations on the Flag model"""
    
    def increase_count(self):
        self.refresh_from_db()
        self.count = models.F('count') + 1
        self.save(update_fields=['count'])

    def decrease_count(self):
        self.refresh_from_db()
        self.count = models.F('count') - 1
        self.save(update_fields=['count'])

    def get_clean_state(self, state):
        """Get integral value representation of state"""
        err = ValidationError(
            _('%(state)s is an invalid state'), 
            code='invalid', 
            params={'state': state}
        )

        # If there's a ValueError or TypeError, or the state is not 
        # among the valid states raise the ValidationError
        try:
            state = int(state)
            if state not in [st.value for st in self.State]:
                raise err

        except (ValueError, TypeError):
            raise err

        return state

    def get_verbose_state(self, state):
        """Get state as string"""
        state = self.get_clean_state(state)
        for item in self.STATE_CHOICES:
            if item[0] == state:
                return item[1]

    def toggle_state(self, state, moderator):
        """Modify flag state if moderator rejects or resolves flag"""
        state = self.get_clean_state(state)

        # Toggle states occurs between rejected and resolved states only
        if state != self.State.REJECTED.value and state != self.State.RESOLVED.value:
            raise ValidationError(
                _('%(state)s is an invalid state'), 
                code='invalid', 
                params={'state': state}
            )
        if self.state == state:
            self.state = self.State.FLAGGED.value
        else:
            self.state = state
        self.moderator = moderator
        self.save()

    def toggle_flagged_state(self):
        """Modify flag state if object if flagged (count is `CONTENT_IS_FLAGGED_COUNT`)"""
        self.refresh_from_db()
        field = 'state'
        
        if self.count == CONTENT_IS_FLAGGED_COUNT and (
            getattr(self, field) not in [self.State.RESOLVED.value, self.State.REJECTED.value]
        ):
            setattr(self, field, self.State.FLAGGED.value)
        else:
            setattr(self, field, self.State.UNFLAGGED.value)

        self.save(update_fields=[field])

flagging/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import JsonResponse
from django.views import View

from .mixins import AJAXMixin, ContentTypeMixin
from .utils import process_flagging_request


class SetFlag(LoginRequiredMixin, ContentTypeMixin, AJAXMixin, View):
    def post(self, request, *args, **kwargs):
        response = process_flagging_request(
            user=request.user, 
            model_obj=self.model_obj, 
            data=self.data
        )
        return JsonResponse(response)

flagging/templates/flag/flag_form.html
<!-- This template overrides the default form used by django-flag-app. -->
<!-- the flag_form.html and flag_icon.html templates used by django-flag-app have been modified, same as the flag.css file. -->
{# NOTE: Any class on any of these templates should not be removed! This may disrupt the javascript functionality. To restyle an element, comment out its style in the flag.css stylesheet. Before modifying any element, be 100% sure that it won't disrupt the js functionality. #}
{# ensure modal and files are in html template #}
{% load i18n %}

{# we must've already verified in the invoking template whether this form should be displayed or not #}
{# so we just display the template with no further conditions #}

{# this element will be used to in the script #}
<span class="d-none js-first-child"></span>
<span class="d-none js-flag-alert-msg">{% trans 'The report request could not be processed. Please refresh the page and try again.' %}</span>
<span class="d-none js-remove-flag">{% trans 'Remove flag' %}</span>
<span class="d-none js-report-content">{% trans 'Report post' %}</span>
<div class="d-inline report-modal-form-combined">
	<div class="d-inline link-danger flag-report-icon js-flag-report-icon"
		data-url="{% url 'flagging:flag' %}"
		data-app-name="{{ app_name }}"
		data-model-name="{{ model_name }}"
		data-model-id="{{ model_id }}"
		data-csrf="{{ csrf_token }}"
		role="button"
	>
		{# span element; don't even dare modify this :) #}
		<span {% if display_title %}title="{% if has_flagged %} {% trans 'Remove flag' %} {% else %} {% trans 'Report post' %} {% endif %}" {% endif %}>
			{% include "flag/flag_icon.html" %}
		</span>
	</div>
	{# use text-start to conteract text-end in question detail templates #}
	<div class="w-100 text-start flag-report-modal js-flag-report-modal">
		<div class="w-75 report-modal-content">
			<span class="report-modal-close">&times;</span>
			<div class="report-modal-flag-form">
				<form class="m-2 p-1 report-modal-form">
					<div class="flag-modal-title">{% trans "Report this post" %}</div>
					{% csrf_token %}
					<div>
						<div class="report-modal-form-reasons">
							{% for reason in flag_reasons  %}
							<div class="form-check mb-3">
								<input
									id="{{ reason.reason }}-{{ random_uid }}"
									type="radio"
									value="{{ reason.value }}"
									class="form-check-input my-2 flag-reason {% if forloop.last %} last-flag-reason {% endif %}"
									name="reason" required
								>
								<label class="form-check-label" for="{{ reason.reason }}-{{ random_uid }}">{{ reason.reason }}</label>
							</div>
							{% endfor %}
						</div>
						<div class="mb-4">
							<textarea class="form-control report-modal-form-info" rows="5" cols="40" name="info"></textarea>
						</div>
						<input type="submit" class="flag-submit-btn" value="{% trans 'Submit' %}" />
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

{% if user.is_mod %}
	{# mod can see number of flags on post #}
	<span class="text-danger fw-bold ms-2">
		({{ num_flags }} {% trans 'flag' %}{{ num_flags|pluralize }})
	</span>
{% endif %}

flagging/templates/flag/flag_icon.html
{% block flag_icon %}
<!-- <svg class="flag-icon {% if has_flagged %}user-has-flagged{% else %}user-has-not-flagged{% endif %}" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" stroke="#427297" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">
    <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"></path><line x1="4" y1="22" x2="4" y2="15"></line>
</svg> -->
{# just display this even on screen readers (no aria-hidden). perhaps hiding it can cause some errs... #}
<i class="ms-1 fa-flag flag-icon {% if has_flagged %} fas user-has-flagged {% else %} far user-has-not-flagged {% endif %}"></i>
{% endblock flag_icon %}